### ISSUE TITLE
NameError raised from trsv_ltu when b is a column vector

### ISSUE THREAD

**Issue by sajanjoseph** [ULAFF/notebooks#8]
In laff.matvec.trsv function, b is a vector with row or column size = 1. At line 75 ,the function trsv_ltu is called as trsv_ltu(A,b) .However,the function laff.matvec.trsv_ltu treats b as a 2D matrix

def trsv_ltu(A,B):
 ...

So, a call 
laff.trsv('Lower triangular','Transpose','Unit diagonal',A,b)
  where b is a column vector
will cause an error message
"dots( -l21, b2, beta1 )
NameError: name 'b2' is not defined"

**Comment by rosatamsen** [comment]
There were a couple variable name typos in trsv_ltu. Thanks!
